version: '2'
services:
    defaultsample-app:
        image: defaultsample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://defaultsample-mysql:3306/defaultsample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    defaultsample-mysql:
        extends:
            file: mysql.yml
            service: defaultsample-mysql
