version: '2'
services:
    defaultmongodb-app:
        image: defaultmongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://defaultmongodb-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=defaultMongoDB
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    defaultmongodb-mongodb:
        extends:
            file: mongodb.yml
            service: defaultmongodb-mongodb
