version: '2'
services:
    reactivemongodb-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/reactiveMongoDB/mongodb/:/data/db/
